[package]
name = "lambda2ts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indoc = "2"
nom = "7"
once_cell = "1.17.1"
